---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
    Default: Cool SG 

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
      KeyName: OfficeKP 
      UserData: | 
                  #!/bin/bash yum update -y yum install -y httpd
                  instanceId=$(curl http://169.254.169.254/latest/meta-data/instance-id)
                  echo "<h1>Hello World from $instanceId</h1>" > /var/www/html/index.html
                  systemctl start httpd
                  systemctl enable httpd

      

  # an elastic IP for our instance
 # MyEIP:
  #  Type: AWS::EC2::EIP
   # Properties:
    #  InstanceId: !Ref MyInstance

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 183.87.175.39/32
