---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
    Default: Cool SG 
  EnvironmentSet:
    Description: select prd or dev
    Type: String
    Default: dev

Mappings:
  RegionMap:
    us-east-1:
      "32": "ami-0947d2ba12ee1ff75"
      "64": "ami-007a607c4abd192db"
    ap-south-1:
      "32": "ami-0e306788ff2473ccb"
      "64": "ami-001e484a60bb07f8d"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      #ImageId: ami-0947d2ba12ee1ff75
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region",32]
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
      KeyName: OfficeKP 
      UserData:
        Fn::Base64: !Sub |
                  #!/bin/bash 
                  sudo su
                  yum update -y 
                  yum install -y httpd
                  instanceId=$(curl http://169.254.169.254/latest/meta-data/instance-id)
                  echo "<h1>Hello World 2 from $instanceId</h1>" > /var/www/html/index.html
                  systemctl start httpd
                  systemctl enable httpd

      

  # an elastic IP for our instance
 # MyEIP:
  #  Type: AWS::EC2::EIP
   # Properties:
    #  InstanceId: !Ref MyInstance

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 183.87.175.39/32

Conditions:
  EnvUsed: !Equals [!Ref EnvironmentSet, dev]
  

Outputs:
  AMIused:
    Description: The AMI used is(here you will instance ID)
    Value: !Ref MyInstance
  EvsType:
    Description: you will prind this only if evs is dev
    Value: Bhai tu dev me hai
    Condition: EnvUsed
  


